### ISSUE TITLE
Feature request OffScreen Canvas

### ISSUE THREAD

**Issue by kasperkamperman** [blueimp/JavaScript-Load-Image#104]
You use canvas for most operations. Did you consider supporting OffScreen canvas:
https://developers.google.com/web/updates/2018/08/offscreen-canvas

It's a Chrome only technology, so maybe it's too much fuss to implement (especially because it would also involve a web-worker then): 

https://caniuse.com/#search=offscreencanvas

**Comment by blueimp** [comment]
Thanks for the suggestion.
In most cases, there is only a single `drawImage` call (which has to be an OnScreen canvas so it can be displayed), however I've added support to use an OffScreen canvas where applicable.
