### ISSUE TITLE
Server side rendering broken with 2.29.0+

### ISSUE THREAD

**Issue by cberg-zalando** [blueimp/JavaScript-Load-Image#106]
We use the library in a SPA using server side rendering. Due to the implementation of the fix for #97 in `js/load-image-orientation.js`, the library is broken in this case as the global `document` object is by default not available on the server.

**Comment by blueimp** [comment]
Thanks for the report @cberg-zalando.

Unfortunately this cannot be lazy loaded, as the check needs to run before any `scale()` call, which is synchronous.

I'm assuming you're doing isomorphic/universal rendering (including the same JS code on both client/server).
In your use case, would the test code still run on client-side if I add a gating check for the document object?

**Comment by cberg-zalando** [comment]
Yep. It is a React based application and as we are using hydrate for the server side rendering, the created HTML is sent to the client and then the hooks, etc. are created. So I assume it also means that this part will also run in the browser.

**Comment by blueimp** [comment]
I've released `blueimp-load-image@4.0.1`.
Please let me know if this resolves the issue.

**Comment by cberg-zalando** [comment]
Yep, its working. Thanks for the quick fix.

**Comment by blueimp** [comment]
Thanks for the confirmation. ☺️
