### ISSUE TITLE
IE11 DOM7009: Unable to decode image at URL: 'blob:'

### ISSUE THREAD

**Issue by AndyOGo** [blueimp/JavaScript-Load-Image#112]
In IE 11 sometimes I get this warning, not always 🤔 

> DOM7009: Unable to decode image at URL: 'blob:37EB3FF1-217A-4BFF-9D6F-33D8DCCF859F'.

Im using again very large images from:
https://effigis.com/en/solutions/satellite-images/satellite-image-samples/

**Comment by blueimp** [comment]
Thanks again for your report @AndyOGo.

Unfortunately I was not able to reproduce this on the [demo](https://blueimp.github.io/JavaScript-Load-Image/), even with the large images from the [reference site](https://effigis.com/en/solutions/satellite-images/satellite-image-samples/).

My theory is that it might have something to do with either an Internet Explorer specific configuration or a configuration of the website in question.

e.g. you could try adding the following snippet to the top of the `head` section of your site to enforce standards mode in IE and see if that helps:

```html
<!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
<![endif]-->
```

**Comment by AndyOGo** [comment]
Thank you @blueimp for your quick answer.

I will try disabling compatability moe explicitly.

**Comment by AndyOGo** [comment]
@blueimp I tried adding `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` explicitly, without luck.
Anyway we use an HTML5 doctype `<!doctype html>`, which triggers the newest rendering engine by default since IE11. Conditional comments are droped since IE10 I believe.
https://docs.microsoft.com/de-ch/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)#document-mode-changes

Now I tested it in 2 environments.
- at `localhost:3000` - only here I get these errors sometimes and sometimes not
  > DOM7009: Unable to decode image at URL: 'blob:A5554FE3-50B0-419C-B5DB-CF2CE6B8B7A8'.
- and on a dev environment, where I don't get any error like this 🤔

**Comment by blueimp** [comment]
I'd say it makes sense to look at the differences between those two environments, e.g. the server headers sent for each HTTP response.

**Comment by AndyOGo** [comment]
@blueimp Alright, I did some more testing.

First I closed IE11 and restartet it.
Since then I even don't get these errors on localhost.

I assume it happenend because I did not always call `revokeObjectURL` during development.
But I have no evidence at hand.

So I will close this issue.

**Comment by blueimp** [comment]
Thanks for posting your resolution. ☺️
