### ISSUE TITLE
How to get exif data of canvas element to fetch geo location in typescript.

### ISSUE THREAD

**Issue by ashutosh925** [blueimp/JavaScript-Load-Image#128]
As given [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/blueimp-load-image/blueimp-load-image-tests.ts)  to define typescript variables and signatures, It's expected to get gps coordinates and exif data. but it only returns ImageHead, OriginalHeight, OriginalWidth. 

loadImage(
  fileOrBlobOrUrl,
  function (img, data) {
    var gpsInfo = data.exif && data.exif.get('GPSInfo')
    if (gpsInfo) {
      // Map of all GPSInfo tags with their mapped names/text as keys/values:
      console.log(gpsInfo.getAll())
      // A specific GPSInfo tag value:
      console.log(gpsInfo.get('GPSLatitude'))
    }
  },
  { meta: true }
)

since data.exif is undefined I'm not able to get geoLocations, how can i can i get this.

**Comment by blueimp** [comment]
Hi @ashutosh925,

I don't manage the TypeScript definitions so cannot provide any info on their correctness.

However the `data.exif` property is only set if the image does have EXIF data available.

Do you have a link to a sample image and have you confirmed that it actually does have EXIF data?

**Comment by ashutosh925** [comment]
actually i was trying to get exif data while capturing image from camera, A canvas element is created when image is captured, since i haven't got exif data for that element, i considered we don't get exif data when any image is captured or canvas is created, rather we only get exif data of those if we have some canvas/image that's already having exif data.

**Comment by blueimp** [comment]
Closing as solved.
