### ISSUE TITLE
how to show  the exif_data  with multiple selected photos

### ISSUE THREAD

**Issue by ieraora** [blueimp/JavaScript-Load-Image#132]
i am successfully using blueimp_to_upload photos to the server. now i would like how to extract and show exif metadata (example ExifIFDPointer). i saw that the new version allows you to view the exif_data for **single photos only**. How can I view the exif_data of **multiple selected photos**? 

Kind regards

**Comment by blueimp** [comment]
Please have a look here on how to use the library:
https://github.com/blueimp/JavaScript-Load-Image#usage
