### ISSUE TITLE
Issue loading an image

### ISSUE THREAD

**Issue by aleporf** [blueimp/JavaScript-Load-Image#137]
There is an issue loading this particular image. (see image link attached below)

[Image example
](https://we.tl/t-9MpRB3opv0)

**Comment by blueimp** [comment]
The issue with that particular image is not its file size (`28.9 MB`).
I have a test file with `58.7 MB` that loads without issues.

The image you provided does not load in Chrome nor Firefox (by opening it in a new tab).
Firefox displays the following error message:
```
The image "PATH/image.jpeg" cannot be displayed because it contains errors.
```

**Comment by aleporf** [comment]
@blueimp Yes, I knew it wasn't a size problem. 
But anyway I wanted to share it to see if there was another issue in the lib.

Thanks for checking it out!

**Comment by blueimp** [comment]
I see. Just opening the file in question in a browser tab is the best way to know if it will load, as the loading itself is just a browser function.
Will close this issue now, but please post here if you have any additional information on why your file is not compatible with browsers.
