### ISSUE TITLE
aspectRatio depending on image orientation

### ISSUE THREAD

**Issue by DJWassink** [blueimp/JavaScript-Load-Image#138]
I was wondering if its possible to crop an image by a certain aspectRatio depending on the fact if an image is made in portrait or in landscape mode.

For example in landscape we might want 16/9 but in portrait maybe 2/3.

Currently this is possible by first loading the image once and checking the width/height and depending on that set the aspectRatio in a second loadImage. This however feels a bit odd and since the data is already know while applying the aspectRatio it could be nice to implement this in the library itself.

**Comment by DJWassink** [comment]
I did fork this repo and added my own (possible dirty) option to achieve what I need:

https://github.com/DJWassink/JavaScript-Load-Image/blob/master/js/load-image-scale.js#L77-L93

**Comment by blueimp** [comment]
Hi @DJWassink!

You don't have to modify the library or call `loadImage` twice to achieve this effect, as the [scaling API](https://github.com/blueimp/JavaScript-Load-Image#image-scaling) already covers your use case:

```js
loadImage(file).then(function (data) {
  if (data.originalWidth > data.originalHeight) {
    // landscape mode
    var scaledImage = loadImage.scale(data.image, { maxWidth: 600 })
    // ...
  } else {
    // portrait mode
    // ...
  }
})
```

**Comment by DJWassink** [comment]
Wow that's actually pretty smart!
Thanks a ton! 

I will see myself out now.
