### ISSUE TITLE
Prevent scale up

### ISSUE THREAD

**Issue by thomasdao** [blueimp/JavaScript-Load-Image#139]
Hi,

Thank you for this fantastic library! I want to scale down the image with the `cover: true` option, but I do not want the image to scale up. Is there an option in the library that only scales down and not up? I search through almost all issues on Github but can not yet find the answers.

Thanks so much!

**Comment by thomasdao** [comment]
One possible solution I can think of is to load the image first to read the width and height and then calculate the maxWidth/maxHeight myself, but just want to check if there's faster way to do it in the library :)

**Comment by blueimp** [comment]
Hi @thomasdao!
Yeah, unfortunately there's no specific option for that, but as you said, you can load the image first and then use the [scale API](https://github.com/blueimp/JavaScript-Load-Image#image-scaling) with options based on the image dimensions.

**Comment by thomasdao** [comment]
Thanks @blueimp, I implemented that and it works fine :)
