### ISSUE TITLE
IE 10 fails on very specific images - example attached

### ISSUE THREAD

**Issue by gordyr** [blueimp/JavaScript-Load-Image#22]
This very well may be a bug or extra security restriction in IE 10 but I have found two images that refuse to work with your demo.

I noticed the problem when developing functionality almost identical to yours for my app.

IE would always fail to read this specific image.  I came across your plugin when searching for a solution and low and behold, your plugin has the same issue.

From what I can ascertain the blob URL is created correctly with createObjectURL as the returned URL appears as any other correctly loading image.

However the image.onload event never fires for it and it is never actually loaded into the browser.  I cannot for the life of me figure out why and what is different about this image to the other 99% of images out there.

It CAN be read by the filereader interface, so a possible solution would be to set an error timeout which will run if the image.onload event has not fired after say 5-6 seconds and restarts the read using the filereader API to create a base64 image instead of a blob URL reference.

It's ugly and hacky would be a temporary fix until we can work out just whats going on.

I have attached one of the images in question.

![1920x1080-desktop-wallpaper-high-resolution-171614870](https://f.cloud.github.com/assets/1015403/422905/7b6342ee-ad3b-11e2-8e9b-80f215bcfaf5.jpg)

**Comment by blueimp** [comment]
Revisiting this in 2020, I cannot reproduce the issue in IE11 on Windows 10.

I don't have IE10 to test anymore, but given that IE11 is the last remaining supported version of Internet Explorer, I feel it's acceptable to close this issue.
