### ISSUE TITLE
Consider using pica to increase the resized image quality

### ISSUE THREAD

**Issue by yaquawa** [blueimp/JavaScript-Load-Image#92]
The default resize downsampling hack results very poor image quality.
Would you please consider support using https://github.com/nodeca/pica instead if it's possible?

**Comment by blueimp** [comment]
I prefer to use the browser-provided image resizing algorithms and have no plans to replace the [Load Image](https://github.com/blueimp/JavaScript-Load-Image) library used.

Although not directly exposed for resizing in jQuery File Upload, [Load Image](https://github.com/blueimp/JavaScript-Load-Image) provides a `downsamplingRatio` [option](https://github.com/blueimp/JavaScript-Load-Image#options) that might improve image quality, when set to a floating point value between `1` and `0`, e.g. `0.5`.

You can test it out with jQuery File Upload by adding the option to the `resizeImage` action here:
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-image.js#L66

Please report back if this option helps with your use case.

And if you would prefer to integrate `pica`, you could do so by overriding the `resizeImage` function here:
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-image.js#L186

**Comment by yaquawa** [comment]
@blueimp Thanks for answering👍🏼
I've tried the default down sampling method before, but I found it's quality is still not so good..
Than I tried pica, which gives me much more better result just like photoshop could do.

My suggestion is "use pica if it found pica" but not depends on it. 

Currently, yes I can use it with pica very easily, but it can be more convenient with supporting pica by default I think.

Also, good to know the `resizeImage` method👍🏼 Thanks.

**Comment by JaegerFlorian** [comment]
@yaquawa I am having a hard time using pica together with blueimp-load-image. Could you please give an example of how you implemented these two to work easily?

**Comment by yaquawa** [comment]
> @yaquawa I am having a hard time using pica together with blueimp-load-image. Could you please give an example of how you implemented these two to work easily?

@JaegerFlorian 

```js
const $avatar_fields = $('.avatar-field');

if ($avatar_fields.length === 0) {
    return;
}

$avatar_fields.each(function () {
    const $avatar_field = $(this);
    const $file = $avatar_field.find('.__file');
    const $canvas = $avatar_field.find('.__canvas');
    const $img = $avatar_field.find('.__image');
    const $input = $avatar_field.find('.__input');

    $file.on('change', function (e) {
        window.loadImage(
            e.target.files[0],
            function (img) {
                pica().resize(img, $canvas[0], {
                    unsharpAmount: 80,
                    unsharpRadius: 0.3,
                    unsharpThreshold: 20
                }).then(function (canvas) {
                    const data_url = canvas.toDataURL("image/jpeg");
                    $input.val(data_url);
                    $img.attr('src', data_url);
                });
            }
        );
    });
});

```
