### ISSUE TITLE
Feature request smoothing

### ISSUE THREAD

**Issue by kasperkamperman** [blueimp/JavaScript-Load-Image#95]
Most browser support smoothing. Would you consider implementing this?
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality

**Comment by blueimp** [comment]
Added in `blueimp-load-image@2.28.0`.
Thanks for the suggestion! ☺️

**Comment by kasperkamperman** [comment]
Cool thanks!

**Comment by kasperkamperman** [comment]
Will you publish this release also to npm?

**Comment by blueimp** [comment]
Already done: https://www.npmjs.com/package/blueimp-load-image/v/2.28.0 ☺️
